apiVersion: apps/v1
kind: Deployment
metadata:
  name: counselor-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counselor-backend
  template:
    metadata:
      labels:
        app: counselor-backend
    spec:
      containers:
        - name: counselor-backend
          image: counselorappacr.azurecr.io/counselor-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
