apiVersion: v1
kind: Service
metadata:
  name: counselor-backend-service
spec:
  selector:
    app: counselor-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
